name: Export Size
on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: antfu/export-size-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          comment_token: ${{ secrets.COMMENT_TOKEN }}
          paths: packages/react,packages/solid,packages/svelte,packages/vanilla,packages/vue
